export enum NavyTypeEnum {
  GENERAL = 'GENERAL', // 일반
  COMPUTER = 'COMPUTER', // 전산
  COOK = 'COOK', // 조리
  AVIATION = 'AVIATION', // 항공
  ELECTRONIC = 'ELECTRONIC', // 전자
  COMMUNICATION = 'COMMUNICATION', // 통신
  MECHANICAL = 'MECHANICAL', // 기관
  CBR = 'CBR', // 화생방
  ELECTRICAL = 'ELECTRICAL', // 전기
  ARCHITECTURE_CIVIL_ENGINEERING = 'ARCHITECTURE_CIVIL_ENGINEERING', // 건축토목
  TRANSPORTATION = 'TRANSPORTATION', // 수송
  MEDICAL = 'MEDICAL', // 의무
}
