export enum AirForceTypeEnum {
  GENERAL = 'GENERAL', // 일반
  ELECTRONIC_COMPUTER = 'ELECTRONIC_COMPUTER', // 전자계산
  CBR = 'CBR', // 화생방
  MEDICAL = 'MEDICAL', // 의무
  MECHANICAL = 'MECHANICAL', // 기계
  VEHICLE_DRIVING = 'VEHICLE_DRIVING', // 차량운전
  VEHICLE_MAINTENANCE = 'VEHICLE_MAINTENANCE', // 차량정비
  COMMUNICATION_ELECTRONIC_ELECTRICAL = 'COMMUNICATION_ELECTRONIC_ELECTRICAL', // 통신전자전기
}